import { Resource } from "../../../auth/_model/resource.model"; 

export class EmployeeModel extends Resource {

	declare id: number;
	empId!: string | null;
	fname!: string | null;
	activeStatus: number = 1;
	buNo!: number;
	joinDate!: Date;
	jobtitleNo!: number;
	gender!: string;
	ssUploadedOn!: Date;
	empName!: string;
	salesrepFlag!: number;
	mpoCommPct!: number;
	slRepGroupNo!: number;
	targetAmount!: number;
	empSignature!: string;
	doctorNo!: number | null ;
	punchCardNo!: string;
	identificationSign!: string;
	confirmationDate!: Date;
	birthRegNo!: string;
	referenceFrom!: string;
	empImagePath!: string;
	salutation!: string;
	lname!: string;
	fatherName!: string;
	motherName!: string;
	spouseName!: string;
	maritalStatus!: string;
	dob!: Date;
	hrType!: number;
	empType!: number;
	jobType!: number;
	bloodGrp!: string;
	religion!: number;
	phoneHome!: string;
	phoneMobile!: string;
	phoneOffice!: string;
	nationality!: string;
	peAddr1!: string;
	peAddr2!: string;
	peAddr3!: string;
	peAddrPost!: string;
	peAddrDist!: number;
	peAddrCountry!: number;
	prCareOfAddr!: string;
	prAddr1!: string;
	prAddr2!: string;
	prAddr3!: string;
	prAddrDist!: number;
	prAddrPost!: string;
	prAddrCountry!: number;
	cashierFlag!: number;
	anaestesiologisFlag!: number;
	nurseFlag!: number;
	sampleCollFlag!: number;
	remarks!: string;
	userName!: string;
	pwd!: string;
	emailPersonal!: string;
	emailOfficial!: string;
	passportNo!: string;
	reportingTo!: number;
	drivinglcNo!: string;
	tinNo!: string;
	faxNo!: string;
	jobtitleDate!: Date;
	peCareOfAddr!: string;
	pabxExt!: number;
	salaryBankNo!: number;
	salaryBankAccNo!: string;
	interest!: string;
	placeOfBirth!: string;
	cardNo!: string;
	contractDate!: Date;
	contractExpireDate!: Date;
	contractPersonName!: string;
	contractRelation!: string;
	contractPhone!: string;
	contractMobile!: string;
	contractEmail!: string;

	husbandName!: string;
	personalNumber!: string |null;

	sinOfficerFlag!: number;
	prepByEmpFlag!: number;


}